<a href="https://colab.research.google.com/github/tintenderete/TFM-Algoritmo-con-redes-evolutivas/blob/main/B_cruce_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import random

In [ ]:
layers = np.zeros(10, dtype=int)
individuos = []
len_gen = 4
num_genes = 5 
size_cadena = len_gen * num_genes
num_individuos = 2

layers_random = []
activations_random = [] 
units_random = []
kernels_size_random = []

rango_minimo_units = 1
rango_maximo_units = 100

rango_minimo_kernel_size = 1
rango_maximo_kernel_size = 4


layers_random = np.random.randint(-1, len(layers), (num_individuos, num_genes))
activations_random = np.zeros((num_individuos, num_genes), dtype=int)
units_random = np.random.randint(rango_minimo_units, rango_maximo_units, (num_individuos, num_genes))
kernels_size_random = np.random.randint(rango_minimo_kernel_size, rango_maximo_kernel_size, (num_individuos, num_genes))

individuos = np.zeros((num_individuos, size_cadena), dtype=int)
individuos[:,::len_gen] = layers_random
individuos[:,1::len_gen] = activations_random
individuos[:,2::len_gen] = units_random
individuos[:,3::len_gen] = kernels_size_random

In [ ]:
individuos[0], individuos[0].shape

(array([ 1,  0, 26,  1,  9,  0, 24,  3,  2,  0, 44,  1,  9,  0, 26,  1,  8,
         0, 20,  1]),
 (20,))

In [ ]:
individuos[1], individuos[1].shape

(array([ 2,  0, 36,  2,  7,  0, 87,  2,  3,  0, 83,  3, -1,  0, 82,  2,  0,
         0, 37,  1]),
 (20,))

In [ ]:
parent1 = individuos[0]
parent2 = individuos[1]

# Cruce de un solo punto (Single-point crossover)

Cruce de un solo punto (Single-point crossover): Se elige un punto en la representación del individuo (a menudo una cadena de bits), y se intercambian todos los bits a partir de ese punto entre los dos padres. Por ejemplo, si los padres son 11001 y 00111, y el punto de cruce es después del tercer bit, los hijos serían 11011 y 00101.

In [ ]:
def single_point_crossover(parent1, parent2):
    crossover_point = np.random.randint(1, len(parent1))  # Choose crossover point
    child1 = np.concatenate((parent1[:crossover_point], parent2[crossover_point:]))
    child2 = np.concatenate((parent2[:crossover_point], parent1[crossover_point:]))
    return child1, child2

In [ ]:
crossover_point = np.random.randint(1, len(parent1))
crossover_point

16

In [ ]:
parent1[:crossover_point], parent2[crossover_point:]

(array([ 1,  0, 26,  1,  9,  0, 24,  3,  2,  0, 44,  1,  9,  0, 26,  1]),
 array([ 0,  0, 37,  1]))

In [ ]:
child1 = np.concatenate((parent1[:crossover_point], parent2[crossover_point:]))
child2 = np.concatenate((parent2[:crossover_point], parent1[crossover_point:]))
child1, child2

(array([ 1,  0, 26,  1,  9,  0, 24,  3,  2,  0, 44,  1,  9,  0, 26,  1,  0,
         0, 37,  1]),
 array([ 2,  0, 36,  2,  7,  0, 87,  2,  3,  0, 83,  3, -1,  0, 82,  2,  8,
         0, 20,  1]))

In [ ]:
parent1, parent2

(array([ 1,  0, 26,  1,  9,  0, 24,  3,  2,  0, 44,  1,  9,  0, 26,  1,  8,
         0, 20,  1]),
 array([ 2,  0, 36,  2,  7,  0, 87,  2,  3,  0, 83,  3, -1,  0, 82,  2,  0,
         0, 37,  1]))

In [ ]:
single_point_crossover(parent1, parent2)

(array([ 1,  0, 26,  1,  9,  0, 87,  2,  3,  0, 83,  3, -1,  0, 82,  2,  0,
         0, 37,  1]),
 array([ 2,  0, 36,  2,  7,  0, 24,  3,  2,  0, 44,  1,  9,  0, 26,  1,  8,
         0, 20,  1]))

# Cruce de dos puntos (Two-point crossover)

Cruce de dos puntos (Two-point crossover): Similar al cruce de un solo punto, pero se eligen dos puntos de cruce y se intercambia la sección entre ellos.

In [ ]:
def two_point_crossover(parent1, parent2):
    crossover_point1 = np.random.randint(1, len(parent1))  # Choose first crossover point
    crossover_point2 = np.random.randint(1, len(parent1))  # Choose second crossover point
    crossover_point1, crossover_point2 = min(crossover_point1, crossover_point2), max(crossover_point1, crossover_point2)

    child1 = np.concatenate((parent1[:crossover_point1], parent2[crossover_point1:crossover_point2], parent1[crossover_point2:]))
    child2 = np.concatenate((parent2[:crossover_point1], parent1[crossover_point1:crossover_point2], parent2[crossover_point2:]))
    return child1, child2

In [ ]:
crossover_point1 = np.random.randint(1, len(parent1))  # Choose first crossover point
crossover_point2 = np.random.randint(1, len(parent1))  # Choose second crossover point
crossover_point1, crossover_point2

(8, 7)

In [ ]:
crossover_point1, crossover_point2 = min(crossover_point1, crossover_point2), max(crossover_point1, crossover_point2)
crossover_point1, crossover_point2 

(7, 8)

In [ ]:
np.concatenate((parent1[:crossover_point1], parent2[crossover_point1:crossover_point2], parent1[crossover_point2:]))

array([ 1,  0, 26,  1,  9,  0, 24,  2,  2,  0, 44,  1,  9,  0, 26,  1,  8,
        0, 20,  1])

In [ ]:
parent1, parent2

(array([ 1,  0, 26,  1,  9,  0, 24,  3,  2,  0, 44,  1,  9,  0, 26,  1,  8,
         0, 20,  1]),
 array([ 2,  0, 36,  2,  7,  0, 87,  2,  3,  0, 83,  3, -1,  0, 82,  2,  0,
         0, 37,  1]))

In [ ]:
two_point_crossover(parent1, parent2)

(array([ 1,  0, 26,  1,  9,  0, 87,  2,  3,  0, 83,  3,  9,  0, 26,  1,  8,
         0, 20,  1]),
 array([ 2,  0, 36,  2,  7,  0, 24,  3,  2,  0, 44,  1, -1,  0, 82,  2,  0,
         0, 37,  1]))

# Cruce uniforme (Uniform crossover)

Cruce uniforme (Uniform crossover): En lugar de intercambiar secciones grandes de la representación, el cruce uniforme intercambia bits individuales con una cierta probabilidad. Por ejemplo, si la probabilidad es 0.5, entonces cada bit tiene una probabilidad del 50% de ser intercambiado.

In [ ]:
def uniform_crossover(parent1, parent2):
    child1, child2 = parent1.copy(), parent2.copy()
    for i in range(len(parent1)):
        if np.random.uniform(0, 1) < 0.5:  # Choose randomly
            child1[i], child2[i] = child2[i], child1[i]  # Swap elements
    return child1, child2

In [ ]:
parent1, parent2

(array([ 1,  0, 26,  1,  9,  0, 24,  3,  2,  0, 44,  1,  9,  0, 26,  1,  8,
         0, 20,  1]),
 array([ 2,  0, 36,  2,  7,  0, 87,  2,  3,  0, 83,  3, -1,  0, 82,  2,  0,
         0, 37,  1]))

In [ ]:
uniform_crossover(parent1, parent2)

(array([ 1,  0, 26,  2,  9,  0, 87,  2,  3,  0, 44,  3,  9,  0, 26,  1,  0,
         0, 20,  1]),
 array([ 2,  0, 36,  1,  7,  0, 24,  3,  2,  0, 83,  1, -1,  0, 82,  2,  8,
         0, 37,  1]))

# Cruce aritmético:

Cruce aritmético: En problemas donde los individuos se representan como vectores de números reales, se puede utilizar el cruce aritmético. Aquí, los hijos se generan como una combinación lineal de los padres. Por ejemplo, un hijo podría ser el 70% del primer padre y el 30% del segundo.

In [ ]:
def arithmetic_crossover(parent1, parent2):
    alpha = np.random.uniform(0, 1)  # Choose a random weight
    child1 = alpha * parent1 + (1 - alpha) * parent2
    child2 = (1 - alpha) * parent1 + alpha * parent2
    return child1, child2

In [ ]:
alpha = np.random.uniform(0, 1)  # Choose a random weight
alpha

0.23536838641854319

In [ ]:
parent1, parent2

(array([ 1,  0, 26,  1,  9,  0, 24,  3,  2,  0, 44,  1,  9,  0, 26,  1,  8,
         0, 20,  1]),
 array([ 2,  0, 36,  2,  7,  0, 87,  2,  3,  0, 83,  3, -1,  0, 82,  2,  0,
         0, 37,  1]))

In [ ]:
[(x1,x2) for x1, x2 in zip(parent1, parent2)]

[(1, 2),
 (0, 0),
 (26, 36),
 (1, 2),
 (9, 7),
 (0, 0),
 (24, 87),
 (3, 2),
 (2, 3),
 (0, 0),
 (44, 83),
 (1, 3),
 (9, -1),
 (0, 0),
 (26, 82),
 (1, 2),
 (8, 0),
 (0, 0),
 (20, 37),
 (1, 1)]

In [ ]:
child1 = alpha * parent1 + (1 - alpha) * parent2
child1

array([ 1.76463161,  0.        , 33.64631614,  1.76463161,  7.47073677,
        0.        , 72.17179166,  2.23536839,  2.76463161,  0.        ,
       73.82063293,  2.52926323,  1.35368386,  0.        , 68.81937036,
        1.76463161,  1.88294709,  0.        , 32.99873743,  1.        ])

In [ ]:
parent1, parent2

(array([ 1,  0, 26,  1,  9,  0, 24,  3,  2,  0, 44,  1,  9,  0, 26,  1,  8,
         0, 20,  1]),
 array([ 2,  0, 36,  2,  7,  0, 87,  2,  3,  0, 83,  3, -1,  0, 82,  2,  0,
         0, 37,  1]))

In [ ]:
np.round(child1)

array([ 2.,  0., 34.,  2.,  7.,  0., 72.,  2.,  3.,  0., 74.,  3.,  1.,
        0., 69.,  2.,  2.,  0., 33.,  1.])

# SELECCION PAREJAS

##Selección proporcional al fitness

In [32]:
import numpy as np

def select_mating_pool(population, fitness, num_parents):
    """
    population: lista con todos los individuos.
    fitness: lista con los valores de fitness de cada individuo.
    num_parents: número de padres que queremos seleccionar.
    """

    # Invierte los valores de fitness
    fitness = 1.0 / fitness

    # Normalizamos los valores de fitness para que sumen 1
    fitness = fitness / np.sum(fitness)
    
    # Seleccionamos los padres usando la función np.random.choice con los valores de fitness como pesos
    idx = np.random.choice(np.arange(len(population)), size=num_parents, replace=False, p=fitness)

    # Devolvemos los individuos seleccionados
    return [population[i] for i in idx]



In [33]:
# Supongamos que tienes una población y su correspondiente fitness
population = ['ind1', 'ind2', 'ind3', 'ind4', 'ind5']
fitness = np.array([33, 56, 101, 34, 12]) 

# Invierte los valores de fitness
fitness = 1.0 / fitness

# Normalizamos los valores de fitness para que sumen 1
fitness = fitness / np.sum(fitness)

print(fitness)

[0.17741171 0.10454618 0.0579662  0.17219372 0.48788219]


In [34]:
# Seleccionamos 2 padres
num_parejas = 20

for i in range(num_parejas):
  parents = select_mating_pool(population, fitness, 2)
  print(parents)


['ind5', 'ind1']
['ind3', 'ind2']
['ind3', 'ind2']
['ind3', 'ind1']
['ind2', 'ind3']
['ind4', 'ind3']
['ind3', 'ind2']
['ind1', 'ind2']
['ind2', 'ind1']
['ind3', 'ind5']
['ind1', 'ind3']
['ind1', 'ind3']
['ind3', 'ind1']
['ind2', 'ind4']
['ind2', 'ind3']
['ind5', 'ind4']
['ind3', 'ind1']
['ind2', 'ind3']
['ind3', 'ind5']
['ind3', 'ind1']


## tournament_selection

In [35]:
def tournament_selection(population, fitness, num_parents, tournament_size):
    # Array para almacenar los índices de los padres seleccionados
    parents = np.empty(num_parents)

    for i in range(num_parents):
        # Seleccionamos los índices de 'tournament_size' individuos aleatoriamente
        tournament_indices = np.random.randint(0, len(population), size=tournament_size)
        
        # Seleccionamos el individuo con el mínimo fitness de entre los seleccionados
        best_individual_idx = np.argmin(fitness[tournament_indices])
        
        # Guardamos el índice del ganador del torneo
        parents[i] = tournament_indices[best_individual_idx]

    return parents

In [36]:
population = ['ind1', 'ind2', 'ind3', 'ind4', 'ind5']
fitness = np.array([33, 56, 101, 34, 12]) 


In [60]:
num_parejas = 20

for i in range(num_parejas):
  p = tournament_selection(population, fitness, 2, 3)
  print(p)

[4. 0.]
[4. 3.]
[3. 4.]
[1. 0.]
[0. 0.]
[0. 4.]
[4. 3.]
[3. 0.]
[4. 4.]
[4. 0.]
[4. 4.]
[0. 3.]
[4. 3.]
[1. 0.]
[3. 4.]
[4. 0.]
[3. 4.]
[4. 4.]
[4. 1.]
[0. 0.]
