<a href="https://colab.research.google.com/github/tintenderete/TFM-Algoritmo-con-redes-evolutivas/blob/main/C_funcion_perdida_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
def perdida_listas(ranking_real, ranking_predicho):
    diferencias = tf.abs(ranking_real - ranking_predicho)
    perdida_total = tf.reduce_sum(diferencias)
    """
    Una opción podría ser cambiar tf.reduce_sum() por tf.reduce_mean() para tomar el promedio de las diferencias en lugar de la suma. Esto hará que la pérdida sea independiente del tamaño del lote de datos.
    """
    return perdida_total


In [ ]:
ranking_real = np.array([[6,3,2,4,5,1]])
ranking_real

array([[6, 3, 2, 4, 5, 1]])

In [ ]:
ranking_predicho = np.array([[1,2,3,6,5,4]])
ranking_predicho

array([[1, 2, 3, 6, 5, 4]])

In [ ]:
diferencias = tf.abs(ranking_real - ranking_predicho)
diferencias

<tf.Tensor: shape=(1, 6), dtype=int64, numpy=array([[5, 1, 1, 2, 0, 3]])>

In [ ]:
perdida_total = tf.reduce_sum(diferencias)
perdida_total

<tf.Tensor: shape=(), dtype=int64, numpy=12>

In [ ]:
perdida_listas(ranking_real, ranking_predicho)

<tf.Tensor: shape=(), dtype=int64, numpy=12>

# asignar más peso a las diferencias que corresponden a números más bajos en el ranking real.

castiga cuando los mejores estan clasificados como peores

In [ ]:
def perdida_listas(ranking_real, ranking_predicho):
    diferencias = tf.abs(ranking_real - ranking_predicho)
    diferencias_ponderadas = diferencias / (ranking_real + 1e-7)  # Añadimos un pequeño número para evitar la división por cero
    perdida_total = tf.reduce_sum(diferencias_ponderadas)
    return perdida_total

In [ ]:
ranking_real, ranking_predicho

(array([[6, 3, 2, 4, 5, 1]]), array([[1, 2, 3, 6, 5, 4]]))

In [ ]:
diferencias = tf.abs(ranking_real - ranking_predicho)
diferencias

<tf.Tensor: shape=(1, 6), dtype=int64, numpy=array([[5, 1, 1, 2, 0, 3]])>

In [ ]:
diferencias_ponderadas = diferencias / (ranking_real + 1e-7)
diferencias_ponderadas.numpy()

array([[0.83333333, 0.33333333, 0.5       , 0.5       , 0.        ,
        3.        ]])

In [ ]:
perdida_total = tf.reduce_sum(diferencias_ponderadas)
perdida_total

<tf.Tensor: shape=(), dtype=float64, numpy=5.166666666666667>

In [ ]:
perdida_listas(ranking_real, ranking_predicho)

<tf.Tensor: shape=(), dtype=float64, numpy=5.166666666666667>

## inversa

castiga cuando los peores estan clasificados como mejores

In [ ]:
ranking_real, ranking_predicho

(array([[6, 3, 2, 4, 5, 1]]), array([[1, 2, 3, 6, 5, 4]]))

In [ ]:
diferencias = tf.abs(ranking_real - ranking_predicho)
diferencias

<tf.Tensor: shape=(1, 6), dtype=int64, numpy=array([[5, 1, 1, 2, 0, 3]])>

In [ ]:
diferencias_ponderadas = diferencias / (ranking_predicho + 1e-7)
diferencias_ponderadas.numpy()

array([[5.        , 0.5       , 0.33333333, 0.33333333, 0.        ,
        0.75      ]])

In [ ]:
def loss_ranking(ranking_real, ranking_predicho):
    ranking_real_float = tf.cast(ranking_real, tf.float32)
    ranking_predicho = tf.cast(ranking_predicho, tf.float32)
    diferencias = tf.abs(ranking_real_float - ranking_predicho)
    diferencias_ponderadas = diferencias / (ranking_predicho + 0.01) # <<<<---------
    perdida_total = tf.reduce_sum(diferencias_ponderadas)
    return abs(perdida_total)

----

In [ ]:
loss_ranking(
    np.array([1,2,3]),
    np.array([1,2,10])
    )

<tf.Tensor: shape=(), dtype=float32, numpy=0.6993007>

In [ ]:
loss_ranking(
    np.array([1,2,3]),
    np.array([10,2,3])
    )

<tf.Tensor: shape=(), dtype=float32, numpy=0.8991009>

In [ ]:
perdida_listas(
    np.array([1,2,3]),
    np.array([1,2,10])
    )

<tf.Tensor: shape=(), dtype=float64, numpy=2.3333333333333335>

In [ ]:
perdida_listas(
    np.array([1,2,3]),
    np.array([10,2,3])
    )

<tf.Tensor: shape=(), dtype=float64, numpy=9.0>

In [ ]:
tf.keras.metrics.mean_squared_error(
    np.array([1,2,3]),
    np.array([10,2,3])
)

<tf.Tensor: shape=(), dtype=int64, numpy=27>

In [ ]:
tf.keras.metrics.mean_squared_error(
    np.array([1,2,3]),
    np.array([1,2,10])
)

<tf.Tensor: shape=(), dtype=int64, numpy=16>