<a href="https://colab.research.google.com/github/tintenderete/TFM-Algoritmo-con-redes-evolutivas/blob/main/C_funcion_perdida_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [48]:
import tensorflow as tf
import numpy as np

In [49]:
def perdida_listas(ranking_real, ranking_predicho):
    diferencias = tf.abs(ranking_real - ranking_predicho)
    perdida_total = tf.reduce_sum(diferencias)
    """
    Una opción podría ser cambiar tf.reduce_sum() por tf.reduce_mean() para tomar el promedio de las diferencias en lugar de la suma. Esto hará que la pérdida sea independiente del tamaño del lote de datos.
    """
    return perdida_total


In [50]:
ranking_real = np.array([[6,3,2,4,5,1]])
ranking_real

array([[6, 3, 2, 4, 5, 1]])

In [51]:
ranking_predicho = np.array([[1,2,3,6,5,4]])
ranking_predicho

array([[1, 2, 3, 6, 5, 4]])

In [52]:
diferencias = tf.abs(ranking_real - ranking_predicho)
diferencias

<tf.Tensor: shape=(1, 6), dtype=int64, numpy=array([[5, 1, 1, 2, 0, 3]])>

In [53]:
perdida_total = tf.reduce_sum(diferencias)
perdida_total

<tf.Tensor: shape=(), dtype=int64, numpy=12>

In [54]:
perdida_listas(ranking_real, ranking_predicho)

<tf.Tensor: shape=(), dtype=int64, numpy=12>

# asignar más peso a las diferencias que corresponden a números más bajos en el ranking real. 

castiga cuando los mejores estan clasificados como peores

In [55]:
def perdida_listas(ranking_real, ranking_predicho):
    diferencias = tf.abs(ranking_real - ranking_predicho)
    diferencias_ponderadas = diferencias / (ranking_real + 1e-7)  # Añadimos un pequeño número para evitar la división por cero
    perdida_total = tf.reduce_sum(diferencias_ponderadas)
    return perdida_total

In [85]:
ranking_real, ranking_predicho

(array([[6, 3, 2, 4, 5, 1]]), array([[1, 3, 2, 6, 5, 4]]))

In [86]:
diferencias = tf.abs(ranking_real - ranking_predicho)
diferencias

<tf.Tensor: shape=(1, 6), dtype=int64, numpy=array([[5, 0, 0, 2, 0, 3]])>

In [87]:
diferencias_ponderadas = diferencias / (ranking_real + 1e-7) 
diferencias_ponderadas.numpy()

array([[0.83333333, 0.        , 0.        , 0.5       , 0.        ,
        3.        ]])

In [88]:
perdida_total = tf.reduce_sum(diferencias_ponderadas)
perdida_total

<tf.Tensor: shape=(), dtype=float64, numpy=4.333333333333334>

In [89]:
perdida_listas(ranking_real, ranking_predicho)

<tf.Tensor: shape=(), dtype=float64, numpy=4.333333333333334>

castiga cuando los peores estan clasificados como mejores

In [90]:
ranking_real, ranking_predicho

(array([[6, 3, 2, 4, 5, 1]]), array([[1, 3, 2, 6, 5, 4]]))

In [91]:
diferencias = tf.abs(ranking_real - ranking_predicho)
diferencias

<tf.Tensor: shape=(1, 6), dtype=int64, numpy=array([[5, 0, 0, 2, 0, 3]])>

In [94]:
diferencias_ponderadas = diferencias / (ranking_predicho + 1e-7) 
diferencias_ponderadas.numpy()

array([[5.        , 0.        , 0.        , 0.33333333, 0.        ,
        0.75      ]])