<a href="https://colab.research.google.com/github/tintenderete/TFM-Algoritmo-con-redes-evolutivas/blob/main/C_funcion_perdida_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
def perdida_listas(ranking_real, ranking_predicho):
    diferencias = tf.abs(ranking_real - ranking_predicho)
    perdida_total = tf.reduce_sum(diferencias)
    """
    Una opción podría ser cambiar tf.reduce_sum() por tf.reduce_mean() para tomar el promedio de las diferencias en lugar de la suma. Esto hará que la pérdida sea independiente del tamaño del lote de datos.
    """
    return perdida_total


In [3]:
ranking_real = np.array([[6,3,2,4,5,1]])
ranking_real

array([[6, 3, 2, 4, 5, 1]])

In [4]:
ranking_predicho = np.array([[1,2,3,6,5,4]])
ranking_predicho

array([[1, 2, 3, 6, 5, 4]])

In [5]:
diferencias = tf.abs(ranking_real - ranking_predicho)
diferencias

<tf.Tensor: shape=(1, 6), dtype=int64, numpy=array([[5, 1, 1, 2, 0, 3]])>

In [6]:
perdida_total = tf.reduce_sum(diferencias)
perdida_total

<tf.Tensor: shape=(), dtype=int64, numpy=12>

In [7]:
perdida_listas(ranking_real, ranking_predicho)

<tf.Tensor: shape=(), dtype=int64, numpy=12>

# asignar más peso a las diferencias que corresponden a números más bajos en el ranking real.

castiga cuando los mejores estan clasificados como peores

In [8]:
def perdida_listas(ranking_real, ranking_predicho):
    diferencias = tf.abs(ranking_real - ranking_predicho)
    diferencias_ponderadas = diferencias / (ranking_real + 1e-7)  # Añadimos un pequeño número para evitar la división por cero
    perdida_total = tf.reduce_sum(diferencias_ponderadas)
    return perdida_total

In [9]:
ranking_real, ranking_predicho

(array([[6, 3, 2, 4, 5, 1]]), array([[1, 2, 3, 6, 5, 4]]))

In [10]:
diferencias = tf.abs(ranking_real - ranking_predicho)
diferencias

<tf.Tensor: shape=(1, 6), dtype=int64, numpy=array([[5, 1, 1, 2, 0, 3]])>

In [11]:
diferencias_ponderadas = diferencias / (ranking_real + 1e-7)
diferencias_ponderadas.numpy()

array([[0.83333333, 0.33333333, 0.5       , 0.5       , 0.        ,
        3.        ]])

In [12]:
perdida_total = tf.reduce_sum(diferencias_ponderadas)
perdida_total

<tf.Tensor: shape=(), dtype=float64, numpy=5.166666666666667>

In [13]:
perdida_listas(ranking_real, ranking_predicho)

<tf.Tensor: shape=(), dtype=float64, numpy=5.166666666666667>

## inversa

castiga cuando los peores estan clasificados como mejores

In [14]:
ranking_real, ranking_predicho

(array([[6, 3, 2, 4, 5, 1]]), array([[1, 2, 3, 6, 5, 4]]))

In [15]:
diferencias = tf.abs(ranking_real - ranking_predicho)
diferencias

<tf.Tensor: shape=(1, 6), dtype=int64, numpy=array([[5, 1, 1, 2, 0, 3]])>

In [16]:
diferencias_ponderadas = diferencias / (ranking_predicho + 1e-7)
diferencias_ponderadas.numpy()

array([[5.        , 0.5       , 0.33333333, 0.33333333, 0.        ,
        0.75      ]])

In [46]:
def perdida_listas(ranking_real, ranking_predicho):
    ranking_real = tf.cast(ranking_real, tf.float32)
    ranking_predicho = tf.cast(ranking_predicho, tf.float32)
    diferencias = tf.abs(ranking_real - ranking_predicho)
    diferencias_ponderadas = diferencias / (ranking_real + 0.01)  # Añadimos un pequeño número para evitar la división por cero
    perdida_total = tf.reduce_sum(diferencias_ponderadas)
    return perdida_total

In [17]:
def loss_ranking(ranking_real, ranking_predicho):
    ranking_real_float = tf.cast(ranking_real, tf.float32)
    ranking_predicho = tf.cast(ranking_predicho, tf.float32)
    diferencias = tf.abs(ranking_real_float - ranking_predicho)
    diferencias_ponderadas = diferencias / (ranking_predicho + 0.01) # <<<<---------
    perdida_total = tf.reduce_sum(diferencias_ponderadas)
    return abs(perdida_total)

----

In [18]:
diferencias = tf.abs(np.array([1,2,3]) - np.array([10,2,3]))
diferencias

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([9, 0, 0])>

In [19]:
diferencias_ponderadas = diferencias / ( np.array([1,2,3])  + 1e-7)
diferencias_ponderadas.numpy()

array([9., 0., 0.])

In [20]:
loss_ranking(
    np.array([1,2,3]),
    np.array([1,2,10])
    )

<tf.Tensor: shape=(), dtype=float32, numpy=0.6993007>

In [21]:
diferencias = tf.abs(np.array([1,2,3]) - np.array([10,2,3]))
diferencias

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([9, 0, 0])>

In [22]:
diferencias_ponderadas = diferencias / (np.array([10,2,3]) + 1e-7)
diferencias_ponderadas.numpy()

array([0.9, 0. , 0. ])

In [23]:
loss_ranking(
    np.array([1,2,3]),
    np.array([10,2,3])
    )

<tf.Tensor: shape=(), dtype=float32, numpy=0.8991009>

In [24]:
perdida_listas(
    np.array([1,2,3]),
    np.array([1,2,10])
    )

<tf.Tensor: shape=(), dtype=float64, numpy=2.3333333333333335>

In [25]:
perdida_listas(
    np.array([1,2,3]),
    np.array([10,2,3])
    )

<tf.Tensor: shape=(), dtype=float64, numpy=9.0>

In [26]:
tf.keras.metrics.mean_squared_error(
    np.array([1,2,3]),
    np.array([10,2,3])
)

<tf.Tensor: shape=(), dtype=int64, numpy=27>

In [27]:
tf.keras.metrics.mean_squared_error(
    np.array([1,2,3]),
    np.array([1,2,10])
)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

# ANALISIS FUNCION DE PERDIDA

In [68]:
def loss_ranking(ranking_real, ranking_predicho):
    ranking_real_float = tf.cast(ranking_real, tf.float32)
    ranking_predicho = tf.cast(ranking_predicho, tf.float32)
    diferencias = tf.abs(ranking_real_float - ranking_predicho)
    diferencias_ponderadas = diferencias / (ranking_predicho + 0.01) # <<<<---------
    perdida_total = tf.reduce_sum(diferencias_ponderadas)
    return abs(perdida_total)

def loss_ranking(ranking_real, ranking_predicho):
    ranking_real_float = tf.cast(ranking_real, tf.float32)
    ranking_predicho = tf.cast(ranking_predicho, tf.float32)
    diferencias = tf.abs(ranking_real_float - ranking_predicho)
    diferencias_ponderadas = diferencias / (ranking_predicho + 0.01) # <<<<---------
    perdida_total = tf.reduce_sum(diferencias_ponderadas)
    return abs(perdida_total)

def mse(ranking_real, ranking_predicho):
    ranking_real = tf.cast(ranking_real, tf.float32)
    ranking_predicho = tf.cast(ranking_predicho, tf.float32)
    diferencias = tf.abs(ranking_real - ranking_predicho)
    perdida_total = tf.reduce_sum(diferencias)
    """
    Una opción podría ser cambiar tf.reduce_sum() por tf.reduce_mean() para tomar el promedio de las diferencias en lugar de la suma. Esto hará que la pérdida sea independiente del tamaño del lote de datos.
    """
    return perdida_total



In [29]:
r_pred = np.array([[18, 28,  3, 23, 29, 20, 15, 21, 22, 27, 10, 14, 13,  6, 19, 11,
         5, 25,  4, 30,  7, 12, 17, 26,  9,  2,  0, 16,  8, 24,  1]])

r_real = np.array([25, 19, 13, 17, 16, 27, 29, 30, 15,  0,  3, 22,  1,  8,  2, 18, 10,
        4, 20,  6, 12, 26,  7, 14, 24, 23, 21, 11, 28,  5,  9])

r_real = tf.cast(r_real, tf.float32)
r_pred = tf.cast(r_pred, tf.float32)

In [30]:
diferencias = tf.abs(r_pred - r_real)
diferencias

<tf.Tensor: shape=(1, 31), dtype=float32, numpy=
array([[ 7.,  9., 10.,  6., 13.,  7., 14.,  9.,  7., 27.,  7.,  8., 12.,
         2., 17.,  7.,  5., 21., 16., 24.,  5., 14., 10., 12., 15., 21.,
        21.,  5., 20., 19.,  8.]], dtype=float32)>

In [31]:
(r_pred + 0.1)

<tf.Tensor: shape=(1, 31), dtype=float32, numpy=
array([[18.1, 28.1,  3.1, 23.1, 29.1, 20.1, 15.1, 21.1, 22.1, 27.1, 10.1,
        14.1, 13.1,  6.1, 19.1, 11.1,  5.1, 25.1,  4.1, 30.1,  7.1, 12.1,
        17.1, 26.1,  9.1,  2.1,  0.1, 16.1,  8.1, 24.1,  1.1]],
      dtype=float32)>

In [32]:
diferencias_ponderadas = diferencias / (r_pred + 0.0001)
diferencias_ponderadas

<tf.Tensor: shape=(1, 31), dtype=float32, numpy=
array([[3.88886750e-01, 3.21427435e-01, 3.33322239e+00, 2.60868430e-01,
        4.48274314e-01, 3.49998266e-01, 9.33327079e-01, 4.28569406e-01,
        3.18180382e-01, 9.99996305e-01, 6.99993014e-01, 5.71424484e-01,
        9.23069835e-01, 3.33327770e-01, 8.94732177e-01, 6.36357844e-01,
        9.99979973e-01, 8.39996696e-01, 3.99989986e+00, 7.99997330e-01,
        7.14275479e-01, 1.16665697e+00, 5.88231862e-01, 4.61536705e-01,
        1.66664815e+00, 1.04994755e+01, 2.10000000e+05, 3.12498063e-01,
        2.49996877e+00, 7.91663408e-01, 7.99919987e+00]], dtype=float32)>

In [33]:
perdida_total = tf.reduce_sum(diferencias_ponderadas)
perdida_total

<tf.Tensor: shape=(), dtype=float32, numpy=210045.19>

In [35]:
ranking = np.arange(35)
ranking

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34])

In [69]:
for i in range(34):
  pred_ranking = np.roll(ranking, -i-1)
  print(pred_ranking)
  loss = loss_ranking(ranking, pred_ranking )
  print("loss ranking: " + str(loss))
  loss = perdida_listas(ranking, pred_ranking )
  print("perdida_listas: " + str(loss))
  loss = mse(ranking, pred_ranking )
  print("mse: " + str(loss))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34  0]
loss ranking: tf.Tensor(3404.1023, shape=(), dtype=float32)
perdida_listas: tf.Tensor(105.07248, shape=(), dtype=float32)
mse: tf.Tensor(68.0, shape=(), dtype=float32)
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
 26 27 28 29 30 31 32 33 34  0  1]
loss ranking: tf.Tensor(3338.8975, shape=(), dtype=float32)
perdida_listas: tf.Tensor(210.05496, shape=(), dtype=float32)
mse: tf.Tensor(132.0, shape=(), dtype=float32)
[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26
 27 28 29 30 31 32 33 34  0  1  2]
loss ranking: tf.Tensor(3255.4473, shape=(), dtype=float32)
perdida_listas: tf.Tensor(314.9437, shape=(), dtype=float32)
mse: tf.Tensor(192.0, shape=(), dtype=float32)
[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27
 28 29 30 31 32 33 34  0  1  2  3]
loss ranking: tf.Tensor(3165.5444, shape=(), dtype=float32)
per

In [ ]:
"""

[25 26 27 28 29 30 31 32 33 34  0  1  2  3  4  5  6  7  8  9 10 11 12 13
 14 15 16 17 18 19 20 21 22 23 24]
loss ranking: tf.Tensor(1046.1537, shape=(), dtype=float32)
perdida_listas: tf.Tensor(2583.227, shape=(), dtype=float32)

"""

In [50]:
a = np.arange(25 ,35)
a

array([25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [56]:
b = np.arange(0 ,25)
np.flip(b)

array([24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,
        7,  6,  5,  4,  3,  2,  1,  0])

In [61]:
np.concatenate((a, np.flip(b)))

array([25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 24, 23, 22, 21, 20, 19, 18,
       17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,
        0])

In [62]:
worst_pred = np.concatenate((a, np.flip(b)))

In [70]:
loss = loss_ranking(ranking, worst_pred )
print("loss ranking: " + str(loss))
loss = perdida_listas(ranking, worst_pred )
print("perdida_listas: " + str(loss))
loss = mse(ranking, worst_pred )
print("mse: " + str(loss))

loss ranking: tf.Tensor(3493.3992, shape=(), dtype=float32)
perdida_listas: tf.Tensor(3493.399, shape=(), dtype=float32)
mse: tf.Tensor(612.0, shape=(), dtype=float32)


In [65]:
np.flip(ranking)

array([34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18,
       17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,
        0])

In [71]:
worst_pred = np.flip(ranking)
loss = loss_ranking(ranking, worst_pred )
print("loss ranking: " + str(loss))
loss = perdida_listas(ranking, worst_pred )
print("perdida_listas: " + str(loss))
loss = mse(ranking, worst_pred )
print("mse: " + str(loss))

loss ranking: tf.Tensor(3493.3992, shape=(), dtype=float32)
perdida_listas: tf.Tensor(3493.399, shape=(), dtype=float32)
mse: tf.Tensor(612.0, shape=(), dtype=float32)
