<a href="https://colab.research.google.com/github/tintenderete/TFM-Algoritmo-con-redes-evolutivas/blob/main/D_funcion_lista_y_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

De momento la funcion para crear la lista sera el ratio de sharpe

In [1]:
import numpy as np

In [24]:
def ratio_sharpe(returns):
  # tu matriz de rendimientos
  #returns = np.random.rand(60, 35)

  # tasa de rendimiento libre de riesgo
  risk_free_rate = 0.01  # ajusta a tu valor apropiado

  # calcular el rendimiento medio anualizado para cada activo
  mean_returns = np.mean(returns, axis=0) * 252

  # calcular la desviación estándar del rendimiento anualizado para cada activo
  std_returns = np.std(returns, axis=0) * np.sqrt(252)

  # calcular el ratio de Sharpe para cada activo
  sharpe_ratios = (mean_returns - risk_free_rate) / std_returns

  return sharpe_ratios


def lista(returns):
  return np.argsort(ratio_sharpe(returns))[::-1]

In [2]:
# tu matriz de rendimientos
returns = np.random.rand(60, 35)

In [3]:
# tasa de rendimiento libre de riesgo
risk_free_rate = 0.01  # ajusta a tu valor apropiado

In [4]:
# calcular el rendimiento medio anualizado para cada activo
mean_returns = np.mean(returns, axis=0) * 252

In [5]:
# calcular la desviación estándar del rendimiento anualizado para cada activo
std_returns = np.std(returns, axis=0) * np.sqrt(252)

In [6]:
# calcular el ratio de Sharpe para cada activo
sharpe_ratios = (mean_returns - risk_free_rate) / std_returns

In [18]:
sharpe_ratios

array([22.4607558 , 27.8879689 , 25.14417971, 24.1179762 , 33.46294005,
       27.03430269, 30.31436246, 29.65396618, 27.57019332, 26.81106578,
       22.41771676, 26.3380875 , 24.90908334, 30.49938934, 26.15294635,
       27.04847143, 24.00334967, 25.13021983, 25.51081149, 28.47885823,
       29.10220358, 30.34154203, 29.19367432, 31.05725711, 29.34887707,
       27.26797652, 31.39978759, 26.14349604, 29.82541818, 26.35673063,
       28.30487328, 24.33130871, 25.03657549, 31.79143868, 31.71678762])

In [10]:
sharpe_ratios.shape

(35,)

In [13]:
ranking = np.argsort(sharpe_ratios)[::-1]
ranking

array([ 4, 33, 34, 26, 23, 13, 21,  6, 28,  7, 24, 22, 20, 19, 30,  1,  8,
       25, 15,  5,  9, 29, 11, 14, 27, 18,  2, 17, 32, 12, 31,  3, 16,  0,
       10])

In [23]:
np.argsort(ratio_sharpe(returns))[::-1]


array([ 4, 33, 34, 26, 23, 13, 21,  6, 28,  7, 24, 22, 20, 19, 30,  1,  8,
       25, 15,  5,  9, 29, 11, 14, 27, 18,  2, 17, 32, 12, 31,  3, 16,  0,
       10])